### ISSUE TITLE
error while ./capture-full-replay

### ISSUE THREAD

**Issue by julientaq** [trahay/bbb-downloader#11]
Hi!

I get this error while trying 
` ./capture-full-replay.sh -o testJu005.mp4 https://scalelite.cloud68.co/playback/presentation/2.0/playback.html\?meetingId\=1b1aacc345b2050c4d62b2f1475734f89494a8e8-1590695733699`

```
│(standard_in) 1: parse error
progress_bar.sh: line 38: [: -gt: unary operator expected
(standard_in) 1: parse error
progress_bar.sh: line 48: [: -ne: unary operator expected
(standard_in) 1: parse error                                              │ 0%
(standard_in) 1: illegal character: N
(standard_in) 1: illegal character: N
usage: sleep seconds
progress_bar.sh: line 29: [: -lt: unary operator expected
```

i ended up with an empty mp4 file, and i can’t find how to make it work.

running on osx catalina, using python 3

**Comment by olberger** [comment]
Uh ?

**Comment by julientaq** [comment]
sorry, `shift+enter` on github just valid the issue 🤒 

won’t do it again sir!

**Comment by julientaq** [comment]
I’m investigating, but is it possible that it’s a server issue?

**Comment by olberger** [comment]
Well... probably some incompatibility with progress_bar on OSX... but I don't have a way to test this.

You could probably try and deactivate the progress bar which isn't essential... if you know how to hack a shell script ?

**Comment by julientaq** [comment]
yes.
removed all the mention about progress bar in the .sh

but somehow the video is not downloaded not generated.

it start recording and after 30sec, it just stops. Here is the result: 

https://pastebin.com/DY7PKayq

**Comment by olberger** [comment]
> removed all the mention about progress bar in the .sh

You've probably removed the wait for the number of seconds of the video length by doing so.

Would you mind sharing your modified variant ?

I guess is that:
```
progress_bar $(echo "$seconds - 10" | bc)
```
should have been replaced with:
```
sleep $(echo "$seconds - 10" | bc)
```

Would that help ?

**Comment by julientaq** [comment]
> You've probably removed the wait for the number of seconds of the video length by doing so.

exactly what happened :-)  \o/

I tried to launch a new download, i’ll keep you posted. Thanks a lot for your help!

**Comment by julientaq** [comment]
And it works!

Apparently the issue comes from the progress bar.
Thanks for taking the time to answer, archive for the openpublishingfest.org will be way better :)

should we let this issue open until the people from progressbar answer?

thanks again!

edit: just finished downloading and converting all the videos i needed.
Huge thanks. 👍

**Comment by vebp** [comment]
Hi, good day.

First of all, thanks a lot fro this wonderful tool.

Having said that,  I though I was having the same problem described up but it is somehow different.

I have a bigbluebutton test server with a test recording. When I do 

sudo bash capture-full-replay.sh https://bbb-example.cl/playback/presentation/2.0/playback.html?meetingId=6dfe6c3d663317795e670804599375901b91b849-1594864176258

a video does appear, but it only has the docker selenium logo.
I changed to 

_sleep $(echo "$seconds - 10" | bc)_


but it didn’t work

the error that I get is:

_Please wait for 36 seconds, while we capture the playback...

/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/lib/promise.js:2626
        throw error;
        ^

TimeoutError: Socket timeout reading Marionette handshake data: Resource temporarily unavailable (os error 11)
Build info: version: '3.141.59', revision: '82b03c358b', time: '2019-04-30T22:04:50'

Driver info: driver.version: unknown
remote stacktrace: 
    at Object.checkLegacyResponse (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/firefox/index.js:521:41)
    at createDriver (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/index.js:170:33)
    at Builder.build (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/node_modules/selenium-webdriver/index.js:632:16)
    at Object.<anonymous> (/home/vito/respaldo_proyectos_lin/p-software/about_bbb/test_mp4/bbb-downloader/selenium-play-bbb-recording.js:21:6)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:67:12) {
  name: 'TimeoutError',
  remoteStacktrace: ''
}
video-rec: stopped
Waiting for video to stop recording...
video-rec                        STOPPED   Jul 18 07:24 PM
Done waiting for video recording to stop.
Video recording stopped_



I’m using an ubuntu 18.04

Thanks a lot for the time

**Comment by trahay** [comment]
Hi,
This looks like a problem similar to this one:
https://github.com/mozilla/geckodriver/issues/1470

You can try upgrading selenium, which may fixe the problem:
$ docker pull elgalu/selenium

François
